target("fortran-lua53")
    set_languages("fortran")
    set_kind("static")
    add_files("src/*.f90")
    set_targetdir("./build")

target("fibonacci")
    set_languages("fortran")
    set_kind("binary")
    add_files("examples/fibonacci/*.f90")
    add_deps("fortran-lua53")
    add_syslinks("lua-5.3")
    set_targetdir("./build")
    before_build(function (target)
        os.cp("$(projectdir)/examples/fibonacci/*.lua", "$(buildir)")
    end)

target("library")
    set_languages("fortran")
    set_kind("shared")
    add_files("src/lua.f90")
    add_files("examples/library/*.f90")
    add_syslinks("lua-5.3")
    set_targetdir("./build")
    set_filename("fortran.so")
    before_build(function (target)
        os.cp("$(projectdir)/examples/library/*.lua", "$(buildir)")
    end)

target("string")
    set_languages("fortran")
    set_kind("binary")
    add_files("examples/string/*.f90")
    add_deps("fortran-lua53")
    add_syslinks("lua-5.3")
    set_targetdir("./build")
