target("fortran-lua53")
    set_kind("static")
    add_files("src/lua.f90")
    set_targetdir("$(projectdir)")

target("fibonacci")
    set_kind("binary")
    add_deps("fortran-lua53")
    add_files("examples/fibonacci/example.f90")
    add_syslinks("lua-5.3")
    set_targetdir("examples/fibonacci/")

target("library")
    set_kind("shared")
    add_files("src/lua.f90")
    add_files("examples/library/fortran.f90")
    add_syslinks("lua-5.3")
    set_filename("fortran.so")
    set_targetdir("examples/library/")

target("string")
    set_kind("binary")
    add_deps("fortran-lua53")
    add_files("examples/string/string.f90")
    add_syslinks("lua-5.3")
    set_targetdir("examples/string/")
